version: '2'

services:
  fix-mariadb-volume-ownership:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /data/mariadb_data:/bitnami
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /data/mariadb_data:/bitnami
    depends_on:
      - fix-mariadb-volume-ownership
  phabricator:
    image: bitnami/phabricator:latest
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    environment:
      - PHABRICATOR_HOST=192.168.89.132
      - PHABRICATOR_USERNAME=admin
      - PHABRICATOR_PASSWORD=root0000
    volumes:
      - /data/phabricator_data:/bitnami
